#!/bin/sh

set -e

# summary of how this script can be called:
#
#   * <postrm> `remove'
#   * <postrm> `purge'
#   * <old-postrm> `upgrade' <new-version>
#   * <disappearer's-postrm> `disappear' <overwriter> <overwriter-version>
#   * <new-postrm> `failed-upgrade' <old-version> <new-version>
#   * <new-postrm> `abort-install'
#   * <new-postrm> `abort-install' <old-version> <new-version>
#   * <new-postrm> `abort-upgrade' <old-version> <new-version>
#
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    purge)
        deluser --quiet --system libvirtdbus || true

        # The call to deluser will normally delete the group as well,
        # but just in case it didn't (for example because the local
        # admin had added more users to the group) let's give it
        # another shot. In this case however we need to check whether
        # the group exists first, because delgroup doesn't deal
        # gracefully with the group not existing
        if getent group libvirtdbus >/dev/null 2>&1; then
            delgroup --quiet --system libvirtdbus || true
        fi
    ;;

    remove|upgrade|disappear|failed-upgrade|abort-install|abort-upgrade)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
