#!/bin/sh

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    configure)
        if [ -z "$2" ]; then
            adduser --quiet \
                    --system \
                    --group \
                    --disabled-login \
                    --home /nonexistent \
                    --no-create-home \
                    --gecos "libvirt-dbus user" \
                    libvirtdbus
        fi

        # After users are created: add user to libvirt group
        # if policykit isn't used to manage access to libvirt sockets then it
        # will use group based permission management with the group "libvirt"
        # being the one to gain access.
        #
        # The socket /run/libvirt/libvirt-sock is default-owned by group
        # "libvirt" in Ubuntu. In Debian this socket managed by policykit and
        # therefore not needed usually, but users might opt-out or for
        # compatibiliy with the sysV handling have it set to use this user.
        #
        # libvirt-dbus itself is considered safe via
        # /usr/share/dbus-1/system.d/org.libvirt.conf so we can allow that
        # by default.
        #
        # Only do that on new installs or upgrades from before 1.4.1-1.
        # This is meant to allow admins to remove the user and not
        # have it re-added each time the package upgrades
        if [ -z "$2" ] || dpkg --compare-versions -- "$2" lt "1.4.1-1"; then
            if getent group libvirt >/dev/null 2>&1; then
                adduser libvirtdbus libvirt
            fi
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
